---
title: "🍥"
output:
  html_document:
    theme: sandstone
    css: "mystyle.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```
```{=html}
<style type="text/css">

body {
      font-size: 13px;
      font-family: "Anonymous Pro", "Helvetica Neue", "Roboto";
}

.hljs {
    font-size: 14px;
    font-family: "Kosugi Maru", "Honoka Maru-Gothic", "Anonymous Pro", "Helvetica Neue";
}

.tocify {
  color: 	#505050;
  font-size: 14px;
  font-family: "Kosugi Maru", "Helvetica Neue", "Roboto";
}

<!-- h1, h2, h3, h4, h5, .h1, .h2, .h3, .h4, .h5 { -->
<!--     font-family: "Kosugi Maru", Anonymous Pro", monospace; -->
<!-- } -->

<!-- code, kbd, pre, samp { -->
<!--     font-family: "Kosugi Maru", "Anonymous Pro", monospace; -->
<!-- } -->

</style>

```
<link rel="preconnect" href="https://fonts.gstatic.com"> 
<link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;1,700&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">

```{css, echo=FALSE}
@media(prefers-color-scheme: light) {
  body {
    background-color: black;
    filter: invert(1);
  }
}
```


# 日本語-案内 {.tabset}

## 日本語-案内 {.tabset}

### 構造

    ・花子さんが来た  
    ・空が青い  
    ・地下鉄が便利だ  
    ・ジョンさんがアメリカじんです  
    ・この辞書は安くて便利だ  
    ・りなさんはきれいでやさしいです  
    ・ウンさんは中国人でキムさんは韓国人です  
    ・私は朝六時に起き、夜十時ごろ寝る  
    ・山田さんはラメンを食べてビールを飲む    
    ・この事件はほぼ終息したし二度と起こることはない  
    ・このバッグは大きいしねだんも手頃だしいいですよ     
    ・家内はフランス語を話せるが私が話せない  
    ・入ってもいいけどしずかにしてくださいね  
    ・あそびたいけれども宿題はまだ終わってない  
    ・私が昨日見た山  
    ・これは友子が作ったケーキだ    
    ・富士山という山  
    ・日本語は曖昧な言葉だという考えは珍しくない  
    ・コンピュータに関する彼の知識は相当なものだ  
    ・ここにこの仕事をするに当たっての注意が書いてある  
    ・よく休むことが必要です  
    ・光子がピアノを弾いているのを聞いた      
    ・ひかるさんが今日は来ることを知らなかった   
    ・誰がそれをするかが問題だ  
    ・いつ帰るかまだ決めていません  
    ・みんながよく聞こえるようにマイクを使ってください  
    ・山田さんは漢字は難しくないと言っている  
    ・人は年を取るにつれて記憶力が衰える   
    ・質問されてもだまっていてください  
    ・小林さんが来たら知らせてください      
    ・私がそこにいた時には異常はなかった    
    ・私は日本留学するために日本語を勉強しています   

------------------------------------------------------------------------

###  初歩 {.tabset}

#### 初舞台 {.tabset}

##### 1

    ・彼女はフランス語が話せる。しかも流ちょうに話せる
    ・ちょっと話をしただけ。 それも小声で話ます  
    ・彼は料理を二人分も食べた。さらに、食後ケーキも食べた   
    ・あの人は頭がいい。そのうえ性格してもいい    
    ・小川さんは仕事が早い。 それに、正確だ  
    ・ノートパソコンは場所を取らない。また、持ち運びにも便利だ    
    ・8時まで日本語の宿題うおした。それから映画をみに出かけた    
    ・僕は駅前の喫茶店に行った。そしてそこで友達を待っていた  
    ・彼は新しい、いい車を持っている。でもめったに乗らない
    ・手紙を出した。しかし返事はこなかった    
    ・二時間待った。けれども、一郎は姿を現さなかった 
    ・手紙を書くか、または電話する
    ・車で行きますか。それとも飛行機で行きますか    
    ・この絵は彼が描いたのでしょうか。あるいはどこかから買って来たのでしょうか 
    ・昨日は京都へ出張していました。それでうちにいなかったんです
    ・私が別れようと言った。すると彼女雨は泣き出した    
    ・日本語を勉強すると役に立つ。だから日本をしている    
    ・おじいさんが大学卒業の日。3000ドルくれた。僕は日本へ行くことにした    
    ・先学期はあまり勉強しなかった。したがって、成績も悪かった    
    ・彼は遅く起きた。その結果、バスに乗り損なった    
    ・そして次は私の番でした  
    ・ところでじんじゃ神社をし知っていますか？
    ・なぜなら彼は病気だったからです
    ・例えば、君は英語が好きですか
    ・金がない。つまり、貧乏なんです
    ・要するに彼らは間違っている  

------------------------------------------------------------------------

##### 2

    ・結局は金の問題だ    
    ・そんなことをするなんて、ほんとに馬鹿というか、困った人だ
    ・相変わらず彼は公園でランチを食べています
    ・どうしてもぼういはチップを取りませんでした
    ・けっきょくだれにもわかりませんでした
    ・もちろんみんなに伝えておきます
    ・もしかしたら来ないかも知れません
    ・なんて可愛い子供でしょう
    ・なるほどいい計画ですね
    ・せっかくためたお金を使ってしまって残念です
    ・とにかく遅いですから帰りましょう
    ・取り敢えず社長の返事待ちましょう
    ・わざわざここまでご案内下さってありがとう
    ・やはり会社の代理人して会議にしなきゃ
    ・やっぱり彼が来なかった
    ・わたしは出かけます
    ・週末は買い物に行きます    
    ・晩ご飯は、たいていうちで食べます    
    ・この問題に関しては、これ以上議論しても無駄だ 
    ・質問されてもだまっていてください
    ・小林さんが来たら知らせてください    
    ・私がそこにいた時には異常はなかった    
    ・私は日本留学するために日本語を勉強しています     
    
------------------------------------------------------------------------    
    
#### 本舞台 {.tabset}

##### 1

    ・今夜は月がきれいですね
    ・さっき田中さんが来ましたよ 
    ・私は友達にワインをあげた
    ・猫がいる
    ・手をさげる    
    ・週末におじいちゃんに会いに行こうよ    
    ・帰りの切符は買ったの？
    ・居酒屋でビールを飲む
    ・新幹線で京都に行こう    
    ・新宿に行きます    
    ・家族と公園にいく
    ・北海道へ行く
    ・ここから出よう
    ・このバスは嵐山駅まで行く
    ・私は英語と日本語を話す
    ・ビーりは飲むが酒は飲まない   
    ・日本はきれいだし好きです  
    ・申し訳ないけど長居できないんですよ
    ・赤ん坊は今空腹だから泣いている    
    ・彼は若いのにしっかりしてるね 
    ・読んでくださいね
    ・とても面白いですよ    
    ・読めよ    
    ・行きますか    
    ・この部屋はちさいわ    
    ・いくぞ   
    ・この魚旨いぜ    
    ・僕も日本語が話せるさ
    ・わからないの？   

------------------------------------------------------------------------    
    
##### 2

    ・これは本です
    ・これを見てくれ
    ・このペンは誰のです
    ・この雨の中を歩いてきたのですか
    ・ここから消えてくれ
    ・ここが私の通った学校だ
    ・ここまでは追ってこないだろう
    ・こちらへどうぞ
    ・こちらを向いてください
    ・こういうこと
    ・こういうふうにやるとうまくいくよ
    ・こんな大雪は珍しい
    ・こんな気持ちになったのは初めてだ
    ・このような話をどこかで聞いたことがある
    ・昔の夏はこんなに暑くなかった
    ・山手線がこんなに遅れることは珍しい
    ・このようにやってごらんなさい
    ・ラケットはこう持ってください
    ・いいかい, 説明書にこう書いてある
    ・それ以前
    ・それ以後
    ・それについては後で述べる
    ・その意気だ
    ・それは僕がなくしたその時計だった
    ・そこが困ったところなんだよ
    ・そこから先は言わなくてもいい
    ・そこまでは考えなかった
    ・そちらのを見せてください
    ・今からそちらへ伺います
    ・そちらの様子はいかがですか
    ・そういう場合には
    ・若者には時々そういうことがあるんだけど
    ・そういうわけさ
    ・そんなことを言ったら誤解されるよ
    ・そんな自分がつくづくいやになる
    ・そんなつもりじゃなかったんだ
    ・そんなに使ったのか
    ・そんなに寒くない
    ・ほんとにそうなんですか
    ・そう考えると
    ・わかりました.そうします
    ・そう言われればそんな気がしてきた

------------------------------------------------------------------------    
    
##### 3

    ・あれが今度の市長です
    ・あれは何の音だろう
    ・あれは何ですか
    ・あの山は何という山ですか
    ・あの後ずっと
    ・あの話はどうなってる?
    ・あそこまで競走しよう
    ・あそこのラーメン屋に入ろう
    ・普通あそこまで言わないよ
    ・あちらに見える山
    ・あちらが新製品でございます
    ・あちらの気候は日本より厳しい
    ・あんな正直な人
    ・あんな美しい絵
    ・私はあんなに偉い人は見たことがない 
    ・ジョッキは、大、中、小のどれがいいですか
    ・ビールは、ジョッキとボトルとどっちがいいですか
    ・どの車がいいですか
    ・どの部屋がいいですかか
    ・どこから来たの
    ・今日はどこからですか
    ・対戦相手はどこですか
    ・どちらへお出でですか
    ・光と音とどちらが速いか
    ・お国はどちらですか?
    ・どういう風に
    ・どういう訳で
    ・それはどういう訳ですか
    ・いったいこれはどういうこと?
    ・その人はどういう性格の人ですか
    ・どんな人ですか
    ・今日はどんな具合ですか
    ・子供にどんな本を読ませたらいいでしょうか
    ・どんなに金があっても
    ・どんなに勉強しても
    ・どうなさいましたか
    ・どうしたの
    ・どう考えてみても
    ・どう考えてみてもそれはおかしいよ

------------------------------------------------------------------------

## 日本語-読書 {.tabset}

### ウェブ・ニュース・平易 {.tabset}

#### 1

**[米を育てる農家の手伝いをするロボット](https://www3.nhk.or.jp/news/easy/k10013051601000/k10013051601000.html)**

    山形県鶴岡市の会社が、薬を使わないで米を育てる農家の手伝いをするロボットを作りました。  
    ロボットの大きさは、幅が1.2m、高さが20cmぐらいです。  
    ソーラーパネルとGPSがついていて、太陽の光から作った電気を使って、自動で動きます。  
    このロボットを田んぼに入れて、スクリューを回すと、水が濁ります。  
    水の中に光が入らなくなって、米が育つのに邪魔になる草が大きくなりません。  
    ロボットを作った人は「将来、米を育てる農家の仕事を少なくすることが必要になります。  
    田んぼの草をとるのは大変な仕事なので、ロボットで手伝いたいです」と話していました。  

------------------------------------------------------------------------

#### 2

**[スーパームーンの皆既月食　月が全部見えなくなる](https://www3.nhk.or.jp/news/easy/k10013053271000/k10013053271000.html)**

    26日、太陽と地球と月がまっすぐに並んで、地球の影で月が見えなくなる皆既月食がありました。   
    この日は、月と地球がいちばん近い日でした。  
    いちばん遠い日と比べると、月が14％大きく見えて、「スーパームーン」と呼ばれています。   
    午後6時44分、皆既月食が始まりました。
    午後8時9分から午後8時28分までの19分は、月が全部見えなくなりました。  
    皆既月食は、空に雲がなかった東北地方や北海道、小笠原諸島などで見ることができました。  
    仙台市で見た小学校6年生の男の子は「去年から楽しみにしていました。   
    初めて見ましたが、きれいでした」と話していました。
    国立天文台によると、次に日本で皆既月食が見えるのは来年の11月8日です。  
    スーパームーンの皆既月食が日本で見えるのは、2033年10月ごろです。 

------------------------------------------------------------------------

#### 3

**[雨がたくさん降って避難が必要なときに出る情報が変わった](https://www3.nhk.or.jp/news/easy/k10013040561000/k10013040561000.html)**

    気象庁は、雨がたくさん降ったときの災害などの危険のレベルを1から5に分けています。  
    危険のレベルが3以上になって避難が必要なとき、市や町や村が出す情報が20日から変わりました。  
    レベル3では「高齢者等避難」という情報が出ます。  
    お年寄りや体に障害がある人などは、避難所などの安全な所に避難を始めてください。  
    レベル4は「避難指示」です。山が崩れたり、川の水があふれたりするときに出ます。  
    山や川の近くなど危険な場所にいる人はみんな避難してください。  
    レベル5は「緊急安全確保」です。もう災害が起こったときや、すぐに災害が起こりそうでとても危険なときに出ます。  
    この情報が出なくても災害が起こることがあるので、レベル4の「避難指示」が出たら、必ず避難することが大事です。  

------------------------------------------------------------------------

#### 4

**[日本は雨の季節　雨がたくさん降った所では気をつけて](https://www3.nhk.or.jp/news/easy/k10013034771000/k10013034771000.html)**

    日本の多くの場所では、雨が多い梅雨の季節になっています。  
    今年はいつもの年より早く梅雨になる所が多くなっています。  
    東海地方と近畿地方ではいつもの年より21日早い16日に梅雨になりました。  
    16日夜からは、雨を降らせる雲が東北地方から九州までの広い地域にかかりました。  
    熊本県では17日の朝、とてもたくさん雨が降りました。  
    特に山都町では午前5時から6時までの1時間に90.5mmの雨が降りました。  
    東北地方の日本海側や北陸地方でも雨がたくさん降りました。  
    秋田県では川の水が増えて、危ない所があります。  
    気象庁は、山や崖が崩れたり、川の水があふれたりする危険があるため、気をつけるように言っています。  

------------------------------------------------------------------------

#### 5

**[渋谷区の職員が駅の周りを歩きながら「外で酒を飲まないで」](https://www3.nhk.or.jp/news/easy/k10013004231000/k10013004231000.html)**

    新しいコロナウイルスの緊急事態宣言が出ていて、東京の渋谷区では酒を出す店は閉まっています。  
    道など外で酒を飲む人が増えていて、ウイルスがうつる心配やうるさいこと、ごみを片づけないことが問題になっています。  
    大型連休が始まる前の28日、夜8時を過ぎると、渋谷駅の前の大きな画面などの明かりは消えました。  
    しかしコンビニの前などには、酒を飲む人たちが集まっていました。   
    このため渋谷区の職員たちが駅の周りを歩いて、1人1人に、酒を飲むのをやめて家に帰るように言いました。  
    そして捨ててあった缶などのごみを拾いました。  
    渋谷区の職員は「外で酒を飲むと気持ちが大きくなって、ほかの人が困ることや、  
    ウイルスがうつるようなことをする人もいます。  
    これからも外で飲まないように言い続けます」と話していました  

------------------------------------------------------------------------

### ラーメン

**[ラーメンからRAMENへ――進化を続ける日本育ちの麺料理](https://www.nippon.com/ja/japan-topics/c09801/?cx_recs_click=true)**

    中国で生まれ、日本で育ち、世界に進出した「ラーメン」

    世界に数多ある料理の中で、「ラーメン」という料理ほど独特な存在はなく、同時に「ラーメン店」という業態も他の飲食店には見られない独特な業態である。

    ラーメンの源流が中国の麺料理にあることは、客観的に見ても間違いのないところである。日本で最初にラーメンを出したと言われる『来々軒』（浅草・1910年創業）は、焼売（シューマイ）や中華丼なども提供する大衆向けの中華料理店であった。ラーメン店のルーツは大衆中華料理店だったのだ。

    戦後になると日本蕎麦（そば）の流れをくむラーメン店も登場するようになった。つけ麺発祥の『大勝軒』のルーツでもある『丸長中華そば店』（荻窪・1948年創業）や、東京ラーメンの代表格として知られる『春木屋』（荻窪・1948年創業）などは、いずれも蕎麦の名産地である信州出身者が創業した店であり、中華料理の文脈は入って来ない。ラーメンのアイコンとしても知られる「なると」は、元来日本蕎麦に用いられていた具材の転用だ。

    さらに日本全国の土地土地の文化と密接につながった「ご当地ラーメン」の存在も見逃せない。地域ごとに異なる歴史を経て生み出されたラーメンの数々は、インターネットの普及とともに全国に知れ渡り、一躍「ご当地ラーメンブーム」が興った。

    中国で生まれた麺料理が日本の食文化と融合し、今ではフレンチやイタリアン、あるいは東南アジアの料理などの技術も包含しながら加速度的に進化し続けている。ヴィーガン（完全菜食主義者）やSDGs（持続可能な開発目標）などライフスタイルや時代のトレンドもキャッチしつつ、世界各国で人気となり、代表的日本食としての地位を獲得した。それでいて、麺もスープも具材も一つとして同じラーメンはない多様性を持つ。このようにものすごいスピードで進化、変化し続けて、バリエーションも無限にある料理はラーメンしかないと言っても良いだろう。

    ラーメン店がなぜビジネス展開しやすいのか

    その背景には高度成長期から半世紀以上にわたり続くラーメンブームと、それによって国民食という地位を獲得してきた歴史がある。1967（昭和42）年に創業した『どさん子』は、みそラーメンブームを起こした立役者であり、フランチャイズによる多店舗展開の先駆者とも呼べる存在である。最盛時には日本全国で約1200店舗を展開し、いち早く海外にも進出を果たしている。その後もチェーン展開をするラーメン店が次々と登場して人気を集めている。

    ラーメンに限らず料理の世界では長い修業経験を経て、初めて店を任されたり店を持てたりするため、人が育たなければなかなか多店舗展開は難しい。そんな中でなぜラーメン店がチェーン展開出来たのか。その要因として大きなものの一つに、ラーメンならではの調理工程があったと考えられる。

    まず、ラーメンには他の料理に比べて調理工程がそもそも少ない。注文を受けてから材料を切ったり焼いたり炒めたりすることはほとんどなく、調理工程だけで言えばタレを入れてスープを注ぎ、麺をゆでて具を乗せるだけだ。むしろラーメンという料理では調理工程よりも仕込みが重要になる。長時間かけてスープを炊いたり、チャーシューを煮たり焼いたり、店によっては麺を打ったりするが、それらは全て店をオープンする前に準備する仕込みだ。

    その中でも味の要となるタレやスープの仕込みは、職人の技術や経験が特に不可欠な工程であるが、セントラルキッチンなどで一括に仕込んだものを供給することで、職人がいなくとも一定以上のクオリティーのラーメンを提供することが可能になり、日本全国においしいラーメン店が爆発的に増えた。さらにインスタントラーメンの普及も相まって、日本人にとってラーメンは誕生から半世紀ほどで国民食となり得たのだ。

    ラーメンから「RAMEN」へ

    国民食となったラーメンは次に海外へと広がりをみせる。今では欧米やアジアなど多くの国と地域に日本のラーメン店が進出を果たしている。中でも米国ニューヨークでは2000年代にラーメンブームが興り、現在100店舗以上のラーメン店があると言われている。

    その先駆として知られるのが、韓国系米国人のデビッド・チャン氏が日本のラーメンを研究して、2004年に開業した『MOMOFUKU』だ。さらに2008年、福岡に本拠を構える『IPPUDO（一風堂）』がオープンしたことで、ニューヨーカーのライフスタイルの中に「RAMEN」という選択肢が加わった。

    ニューヨークでラーメンが流行した理由についてはいくつもの推論がある。一つは日本の文化やサービスなどが海外で人気を集めている、いわゆる「COOL JAPAN」のムーブメントがある。アニメやマンガ、ゲームなどの「Japanese Culture」の一環として、ラーメンにもスポットが当たった可能性は高い。例えばアニメの中に出てきたラーメンを見て興味を持ったという人も少なくないのだ。さらに日本食に対する好意的なイメージも後押ししているはずだ。

    また、日本ならではの「おもてなし」の精神がラーメン店のホスピタリティに寄与することで、レストランと同等の評価を得たことも大きい。それまでの中国やアジアの麺料理はファストフードとしての扱いがされており、当然のことながら材料原価も販売価格も安い。しかし日本のラーメンは原価もかかっているので販売価格も高くなる。同じ麺料理というカテゴリで勝負すると価格で勝ち目がなくなる。差別化を図る意味でも日本のラーメン店が日本と同じかそれ以上のサービス、接客を充実させたことが功を奏した。

    豚骨ラーメンが世界を制した理由とは

    そのような背景がありつつも、やはりラーメンやラーメン店自体に魅力がなければ、飲食店が多いニューヨークの街で受け入れられることはなかっただろう。その魅力の一つとして考えられるのは「豚骨スープ」が持つ圧倒的な旨味（うまみ）だ。

    豚の骨を炊いたスープはイノシン酸を豊富に含んでいる。そこに昆布などのグルタミン酸やシイタケなどのグアニル酸を含んだタレを加えることで、旨味の相乗効果が生まれる。旨味こそ日本食最大のアドバンテージであり、他の料理ではなかなかまねのできないことだ。

    実際、前述した『IPPUDO』をはじめ、海外に進出している日本のラーメンチェーンの多くは豚骨ラーメン店である。また、宗教上などの理由で豚骨スープを出せないエリアでは鶏を白濁するまで煮込んだ「鶏白湯（とりぱいたん）」と呼ばれるスープで提供している店が多い。今でこそ白濁していないスープを出すラーメン店も増えているが、ブレイクスルーするタイミングで豚骨スープや鶏白湯などの「白濁スープ」が与えた影響は少なくないと考えられる。

    豚骨スープとは、その名の通り豚の骨を煮込んで白濁乳化させたものだ。これは他の料理には見られないスープであり、しかも一杯あたり300cc以上もの量が提供されるような料理はなかなかない。そのため当初米国や欧州では、ラーメンは麺料理というよりもスープ料理として認知されていた。日本では麺は全て食べてスープを残すことがあるが、欧米ではスープは全て飲み干されて麺が残されることもある。

    これまで海外では日本のラーメンを模倣したり、日本のラーメン店が進出したりするケースがほとんどであったが、最近では、その国オリジナルのラーメン店も生まれている。日本各地のご当地ラーメンのように、その国の文化や食生活に根付いた、その国ならではの個性豊かなラーメンが、今後急速に増えていくことだろう。

------------------------------------------------------------------------

### 藤:紫色の花

**[【書評】紫色の高貴な花が織り成す文化誌：有岡利幸著『藤と日本人』](https://www.nippon.com/ja/japan-topics/bg900282/)**

    亀戸天神社「藤まつり」の賑わい

    学問の神様、菅原道真公を祀（まつ）る東京・江東区の亀戸天神社は“東京一の藤の名所”といわれる。新型コロナウイルスの3度目の緊急事態宣言が発令される直前の4月23日の昼下がり、境内はマスク姿の参拝客や観光客らで賑わっていた。

    亀戸天神社は「藤まつり」の最中とあって、花房を垂らした藤が一斉に咲き誇り、淡い芳香が漂う。朱色の太鼓橋とカメたちが甲羅干しする心字池、快晴の蒼穹（そうきゅう）をバックに薄紫色と新緑の藤棚がよく映える。北西方向には東京スカイツリーもくっきりと見えた。

    いつ誰が植えたものかは不詳であるが、境内の心字池に架けられた太鼓橋のたもとに育てられている藤が江戸時代から有名で、『江戸砂子』『江戸名所図会』『江戸名所花暦』などに亀戸天神の藤として取り上げられている」――。本書には、亀戸天神社をはじめ日本各地の藤の名所が豊富なカラー写真や絵図入りで登場する。

    ノダフジとヤマフジの2種自生

    鑑賞用の藤棚は江戸時代から作られたといわれる。日本では現在、ゴルフ場のティーショットを打つ場所の近くに藤棚があるのは珍しくない。評者は中国の北京郊外のゴルフ場でも藤棚を見た。出張先の英国のオックスフォード大学では20年前の5月、薄紫色の藤の花が咲いていた。そもそも藤にはどんな種類があるのか。

    「フジ（藤）とは、落葉するつる性樹木、マメ科フジ属（学名Wisteria）の総称である」。本書ではこう定義する。

    「フジ属は日本、東アジア、北アメリカにおよそ八種があり、日本にはそのうちの二種、フジ（別名ノダフジ、学名Wisteria floribunda。種の名称のフロリブンダは花が多いという意味）とヤマフジ（学名Wisteria brachybotrys）が自生している」

    「藤」をどう表記するかは難しい。著者は「フジ属の総称の『フジ』と、特定の種であるフロリブンダを指す和名『フジ』との混乱を避けるため、本書では特に種を定めずよぶときには『フジ』または『藤』、フロリブンダ種を指すときには別名の『ノダフジ』を用いることとする」

    「東京周辺では山で生育しているフジのことを栽培種と区別するためにヤマフジ（山藤）とよんでいるが、正しい種名はノダフジである。一方、日本自生種のヤマフジも里にもってきて栽培される。栽培されているものでも種名はヤマフジである。ややこしいことだが、山に生えているからといって単純にヤマフジとはいえないのである」

    フジ（ノダフジ）は主に本州、四国、九州に分布し、ヤマフジは近畿以西、四国、九州に分布するとされる。別名ノダフジ（野田藤）の名称の由来は「摂津国西成郡野田村（現・大阪市福島区玉川）に生育していた藤から起っており、牧野富太郎によって命名された」。摂津の野田には古来よりフジが群生し、文禄3年（1594年）には「太閤豊臣秀吉も藤の花見に訪れ茶会を開いたことが伝わる」という。

    日本原産のノダフジとヤマフジの見分け方は簡単だ。「つるの巻き方が違っていることで判別する。ノダフジの巻き方は上から見て時計回りに巻きつき登っていく。ヤマフジは反時計回りである」

    縄文時代からの藤布と『古事記』

    藤は部位によって、様々な用途に役立つ。「成形して器具類を作成しようとする場合や、藤の繊維を利用しようとする場合は幹がその部材となる。藤を食用とする場合は花と葉が材料となる。薬の場合は幹の瘤と根と種子が材料となる」

    「藤は花の美しさとともに樹皮が利用される有用性の高い樹木として縄文・弥生のむかしから日本人に親しまれ大いに利用されてきた」歴史がある。

    縄文時代から、山野に自生する藤の繊維から「藤布（ふじふ）」が織られてきた。本書によると、『万葉集』にはフジを詠んだ歌が題詞を含めて28首ある。次はそのうちのひとつだ。

    「須磨の海人（あま）の塩焼衣（しおやきぎぬ）の藤衣（ふじころも）　間遠（まどお）にしあればいまだ着なれず」

    「フジの繊維は織り上げると白い衣となったが、ゴワゴワして肌触りが良くなかった。庶民の仕事着とされたり喪服として着用された。取り上げた歌では須磨（すま）の浜（現・神戸市須磨区須磨海岸）で塩をつくり出すために働く漁師の作業衣とされているが、和歌を詠みながらも、まだ着心地が悪いと愚痴をこぼしている」

    「わが国の文献にフジが最初に登場するのは、正史ともいえる『古事記』の中である」。イズシオトメという女神は誰からの求愛も拒否していたが、ハルヤマノカスミオトコが藤衣をまとい弓矢を持って行くと、着衣も弓矢にも藤の花が一斉に咲き、女神と結婚できたという話である。

    著者は「何らかのはずみでイズシオトメの結婚したくないと閉ざされた心が、結婚してもいいわと開かれたのである。そのきっかけとなったものが藤の花であった」と解説している。

    諏訪大社の御柱も曳くフジの縄

    長野県の諏訪湖の周辺に境内地をもつ諏訪大社。７年目ごと、寅（とら）と申（さる）の年に開く「御柱（おんばしら）祭」（正式名称は式年造営御柱大祭）は勇壮な祭として全国的に有名だ。1200年以上も続く諏訪大社最大の神事で、次回は来年に予定されている。

    奥山から樅（もみ）の巨木を伐（き）り出し、大勢の氏子たちが社頭まで曳（ひ）いていく縄は「ノダフジの糸でなわれていた（ヤマフジよりもノダフジの方が繊維が強い。今日は一部の地区で伝統が継承されている）」と著者は記述する。

    藤の繊維をより合わせてつくる縄はとても丈夫だ。「藤づるはねじれてもなかなか砕けることがなく、きわめて強靭な素材なので縄とされ、綱の代用として木材を川の上流から流して運ぶ筏（いかだ）をつないだり、薪や炭俵を束ねるのにも用いられた」

    奈良時代から庭での栽培が普及

    「わが屋戸（やど）の時じき藤のめずらしく　今も見てしか妹（いも）が笑（え）まひを」

    『万葉集』を編纂したとされる大伴家持（おおとものやかもち）が詠んだ歌からも、奈良時代には山野の藤を観賞用として家の庭などに移植する技術が普及していたことがうかがえる。

    「藤の木から垂れ下がる花房が芳しい香りをあたりにただよわせ、花房のまわりに蝶やクマバチが羽音をひびかせながら乱舞している。平城の京の街中にある家の庭にはそんなフジの花が咲いていたことであろう」。著者はかつての平城京の光景に思いをめぐらす。

    『源氏物語』にみる平安貴族と藤

    第50代天皇、桓武天皇（在任781～806年）は平城京から784年に長岡京を造営、794年には平安京に遷都した。鎌倉幕府成立まで約400年続く平安時代、藤は気品ある特別な花として天皇や貴族に愛された。

    藤紫（ふじむらさき）という言葉があるように藤の花は紫色。「日本では色の格付けとしては最も位が高いとされている」

    著者は『源氏物語』を引用しながら、平安貴族と藤とのかかわりを考察している。物語の主人公、光源氏（ひかるげんじ）の義母で初恋の相手「藤壺の女御」、その姪で最愛の妻となった「紫の上」……。キーワードの「藤」と「紫」は、高貴で美しい女性の象徴にもなっている。

    作者、紫式部が仕えていた中宮彰子は公卿(くぎょう)、藤原道長の長女で、「藤壺」とよばれた。藤原氏にゆかりのある「藤」が物語の背景にあると著者は分析する。因みに「壺」は中庭のこと。中宮彰子の住いの中庭には藤が植えられていたという。

    「紫式部自身も身分は低いものの藤原氏の出身である。それ故王朝文化ともいわれる平安文化を築き、さらにその庇護者である藤原氏を誇りとするものであったのだろう。『源氏物語』そのものは、藤の賛歌となっているといって差し支えないであろう」

    藤の字がつく名字や地名は多い

    藤原氏の始祖は、7世紀中葉の「大化の改新」の功臣とされた中臣鎌足（なかとみのかまたり）。天智天皇が「当時の官位の最高位である大職冠（たいしょくかん）を授け、内大臣に任ずるとともに藤原の姓を与えた。藤の家紋はその際に天智天皇から下賜された」と伝えられる。

    「藤原という姓は、大化の改新の舞台となったところが藤原京であったので、功を賞して姓を与えるにはその功労のあった藤原京にちなんだものがよかろうという天皇の計らいによるものであろう」。著者はこう推理している。

    『樹木と名字と日本人』などを著した著者は、樹木名のついた人名や地名を調べたことがある。「神聖な樹木として取り扱っている松には及ばないが、梅や桜、杉や檜、樫、柏、柳などよりも藤の方が多かった」という。

    「藤の字を持つ名字は種類も数も多い。地名の方でも名字と同様の傾向であった。桜や梅ほど花の美しさが評価されない藤が、なぜこれほどまでに名字や地名に用いられているのか。それは日本人の生活文化のなかに藤が深くくいこんでいるということだろう」

    藤をデザインした家紋も多種多様だ。「藤丸がもっとも多いが、花房が垂れ下がったものを『下がり藤』、上に向いたものを『上がり藤』とよんでいる」。図柄はこのほか「花藤紋」、「枝藤紋」、「蔓藤（つるふじ）」、「散藤（ばらふじ）」などに分類される。

    「藤紋を用いた公家には九条・二条・一条・醍醐・正親町（おおぎまち）・裏辻・富小路の各家、武家では藤原秀郷流（ながれ）の内藤・佐藤・武藤・近藤・尾藤・首藤・安藤・伊藤・後藤、藤原利仁流の進藤・斎藤・加藤などがある」。「藤原氏でも藤紋を用いない者もかなりある」という。

    酒好きの「松と藤」の組み合わせ

    日本では「松と藤」が対（つい）で登場することがしばしばある。12世紀前半に製作されたとみられる『源氏物語絵巻』蓬生（よもぎう）には大きな松に懸かる藤の花が描かれている。

    歴史を遡ると、著者は奈良時代にも松と藤を組み合わせた絵が存在したとの説を唱える。「楽器の面に描かれた小さな絵ではあるが、松の梢から花房を垂らした藤が描かれている」。楽器とは、奈良の正倉院に宝物として収蔵されている四弦の撥弦(はつげん)楽器「阮咸（げんかん）」である。

    その絵自体は唐からの渡来作品であるのか、日本で描かれたものかは謎とされている。著者は「日本で製作された」との立場だ。その理由は「奈良朝期の文化文明の師である中国で藤は嫌われていたが、わが国では権力権威の最高位のところにある天皇周辺は、藤の花を氏の花として最も尊んでいる藤原氏の勢力で塗りつぶされていた」からだ。

    著者は松と藤の共通点にも言及している。「樹木の王様とも称される松と同じように、藤も酒好きの樹木」ということだ。「藤花は水揚げの悪い花で、酒がないと水の中に生けてもすぐに枯れてしまう」。昔から、藤を生けるときは酒に浸すとよいといわれている。

    蛇に見立てられる藤と「鬼滅の刃」

    「八入折（やしおおり）の酒にひたせばしをれたる藤なみの花よみがへり咲く」

    明治時代の俳人・歌人、正岡子規が病床で詠んだ歌だ。「見舞客が持ってきた藤の花が萎（し）おれてきたので切口を酒にひたしてやると、また生気がもどって生き生きとしてきたというのである」

    子規は亀戸天神社にも足を運ぶなど、優美な藤の花を愛でた。しかし、つる性植物の藤には全く別の顔もある。

    「樹木の幹に巻きついた太い藤のつるは、ちょうど蛇がトグロを巻いた様子とも見立てられる」

    さらに「トグロを巻いているところから上方の藤のつるから小枝が分かれ出て、その先端から花房が長く垂れゆらゆらと風に揺れているさまは、あたかもトグロを巻いた蛇が鎌首をもちあげ、細長い舌をチロチロッとうごめかしているとも見うけられる」

    著者は、民俗学者・谷川健一の著書『蛇』を引用し、「藤は蛇を意味するというのが、日本古来の伝統的な約束だ」と指摘する。

    本書では、平安時代後期に起きた「前九年の役」の際、出羽国柴田郡（現・宮城県柴田郡）の白鳥神社の大木の藤が大蛇に変身したという「奥州の蛇藤（じゃふじ）」伝説などを紹介している。

    毎年5月8日に開催される大善寺（山梨県甲州市勝沼町）の「藤切り祭」も４ページ以上を割いて詳述している。1300年前から伝わる奇祭で、大蛇に見立てた藤づるを修験者が切り落とし、それを持ち帰るとご利益があるといわれ、毎年壮絶な奪い合いが繰り広げられる。大善寺によると、今年はコロナ禍で、感染予防のため奪い合いを禁止するなど規模を縮小するという。

    昨今、国内外でヒットした漫画・アニメ映画の「鬼滅の刃」では藤の花が鬼を封じるものとして描かれている。鬼と藤の関係とはいかなるものか。藤をめぐる文化誌として集大成した本書は最終章「藤花は鬼を封じるか」で、大団円を迎える。

------------------------------------------------------------------------

### 遊女たち

**[守貞が見た江戸の遊女たち : 『守貞漫稿』(その9)](https://www.nippon.com/ja/japan-topics/g01083/)**

    花魁と太夫の違い

    三都（京都・大坂・吉原）には、それぞれ幕府が公認した遊郭があった。京都は島原、大坂は新町、そして江戸は吉原である。上方育ちの守貞は島原・新町には馴染みがあったかもしれないが、吉原は未知の世界だった。そして、江戸に来て、京坂とは違う吉原の独特な世界を垣間見ることになる。

    守貞はまず、京坂と吉原の最高級の遊女の違いに注目し、絵を描き、解説文を記した。

    右が「今世京師ノ島原及ビ大坂新町太夫職游女之扮」（京坂）。
    左が「今世江戸吉原游女之図」（江戸）。
    いずれも絢爛豪華であることは変わりないが、帯の結び方、髪の結い方や櫛（くし）や簪（かんざし）は東西で流行が違っていたのだろう。守貞はその違いを詳細に絵と文字で詳細に記している。

    島原と新町は「太夫」（たゆう）、吉原は「花魁」（おいらん）と、呼び方が異なる。太夫と花魁は混同されることが多いが、どちらも遊郭最高位の女性を指すもので、そもそもは三都とも「太夫」と呼んでいた。だが、吉原では太夫の数が次第に減り、宝暦年間（1751〜1764）に実質的に消滅する。

    その後、下級の遊女たちが、姉貴分の遊女を「おいらの所の姉さん」と呼んだことから、いつのまにか「おいらん」＝最高位の遊女「花魁」を指すようになったという説がある。

    真相ははっきりしないが、いずれにしても吉原では太夫に代わって花魁が現れ、一方、京坂では太夫が存続し続けたため、呼称も変わらなかった。

    守貞もその辺は熟知していたらしく、「（江戸でも）昔ハ太夫ト称ス。今ハ花魁ト書キ、オヒラント訓ス」とある。

    供（とも）の者も違う。太夫と花魁が外を歩く時（といっても、遊郭の中のみ）は、京坂は「引舟（ひきふね）」と呼ばれる若い遊女が供をした。対して江戸では、「禿（かむろ）」と呼ばれる少女が花魁に付き添っている。

    引舟が10代半ばの「新造」（詳細は後述）であるのに対し、禿はもっと幼少時から、遊郭に売られてきた子などから売れっ子の遊女となりそうな者を抜擢し、花魁の間近で立ち居振る舞いや行儀作法、読み書きなどを学ばせた。

    さらに、帯の結び方が違う。どちらも前で結んでいるのは同じで、これは「一夜妻」の意味だとされるが、太夫の帯は横に広がっており、「心」の文字を表している。「心は簡単には解けませんよ」という意図だったという。対して花魁は、帯を前にだらりと垂らす。そのほうが見栄えするからだったという説が一般的だ。

    最高級の花魁は一晩13万円

    遊女にはランクがあった。吉原でいえば、花魁と呼ばれるのは上級遊女だけであり、その下に下級（新造）、禿と続く。厳密な階級社会だったのである。

    江戸の遊女の階級

    花魁は高嶺の花であり、中でも最高位の「昼三」（ちゅうさん）と一晩を過ごすには、最低で約一両一分（約13万円）を必要としたと、江戸文化評論家の永井義男氏は指摘している（一両を約10万円、一分を約2万5000円として計算）。

    しかも、通常は3回通って、ようやく馴染み客として認められる。馴染みとなると、今度は「床花」（とこはな）という祝儀を渡し、帯や簪をおねだりされたら、もちろんプレゼントする。その間には店の従業員たちにチップもはずむ。現代でいえば、恐らく、100万円単位の金をつぎ込んでやっと床入りである。とても庶民には手が出なかった。

    もっとも、3回通って認められるというのは洒落本などを通じて広まった一種の都市伝説であり、花魁も高額な金さえ払えば初会の客と床入りしていたようだ。江戸庶民には一晩で10万円を超える豪遊をできる男などめったにいなかったため、こうした伝説が生まれたのかもしれない。

    禿から新造へと出世するものの…

    庶民の相手は、下級遊女の新造だった。詳細なデータはないが、上級遊女の最低ランクが約一分（約2万5000円）だから、それ以下だったろう。

    新造は、見習いを経た禿が10代半ばに成長した姿である。15歳で遊女としてデビューする者を「留袖（とめそで）新造」、17歳デビューを「振袖（ふりそで）新造」と呼んだ。振袖新造は、将来、上級へとランクアップできるものもいる花魁候補で、同じ新造でも格上だった。「吉原振袖新造之扮」には、花魁と比べると、着物も髪を飾る簪や笄（こうがい）もシンプルなまだ初々しい姿が描かれている。

    新造は、妓楼（遊女がいる店をこう呼んだ）の1階にある格子越しの張見世（はりみせ / 客が遊女たちを品定めするショーウインドウ）に座り、客からの指名を待つ。吉原のメインストリートの仲の町には、張見世がずらりと並んでいた。

    客は張見世で遊女を選ぶと、2階に通される。これを登楼（とうろう）といった。

    2階は遊女と客、仲居などでごった返している。まずは遊女と酒を酌（く）み交わすのが一般的だが、酒宴も抜きに床入りに向かう者もいた。こうした客を「床急ぎの客」と呼んだそうだ。花魁は店の奥に別格の座敷を与えられていたので、ここに描かれているのは新造や禿で、部屋は共用の「廻し部屋」だろう。

    守貞は、吉原でどのように遊んだのだろう。推測の域を出ないが、江戸へ単身赴任していただけに、馴染みの遊女はいたかもしれない。遊女を描いた守貞の絵は熱意に満ち、彼女たちへの愛着を感じさせる。

    バナー写真 : 『今世官許遊女 褻之扮』（「守貞漫稿」）。「官許」は、幕府公認の意。「褻之扮」は外出用ではなく、室内で過ごす際の姿を指す

------------------------------------------------------------------------

### 京都:歴史文化都市

**[京都（前編）：疫病や戦火、災害に見舞われた1200年の歴史文化都市](https://www.nippon.com/ja/japan-topics/g00993/)**

    疫病と戦った先人たちの記憶

    2020年、新型コロナウイルスが世界中の人々の活動を抑制し、人の流れが滞った。日本を代表する歴史文化都市であり、国際観光都市として知られる京都も例外ではない。春から夏にかけて内外からの訪問が途絶え、名所や観光地から人々の姿が消えた。ようやく秋になって、感染症対策に最大限に心を配りながら国内の旅行者を受け入れるようになった。しかし21年になっても感染拡大の動きは収まりそうになく、かつてのように国内外から観光客がやってくるのはしばらく先のことになりそうだ。

    もっとも京都で暮らす人々が、疫病に襲われるのは今回が初めてではない。古くは9世紀の中頃にも伝染病がまん延し、多くの人が命を落とすことがあった。朝廷は、863（貞観5）年、神泉苑で「御霊会（ごりょうえ）」と称する儀礼を執り行った。当時、疫病は恨みを残して亡くなった人々の怨霊の祟（たた）りが原因であると考えられていた。そこで薬師如来の垂迹（すいじゃく＝仏の仮の姿）である除疫神・牛頭天王（ごずてんのう）を祀（まつ）り、人々の無病息災を祈念した。

    しかし日本各地ではその後も不吉な出来事が続く。864（貞観6）年には富士山が大噴火を起こし、869（貞観11）年には東日本大震災に類似すると言われる貞観地震が三陸沖で発生、津波によって多くの犠牲者が出た。都での疫病に加えて、東国での自然災害が人々の不安を募らせた。朝廷は国の数である66本の鉾（ほこ）に諸国の悪霊を宿らせたのち、その汚れを払う「御霊会」を再び行った。この時の祭礼が、のちに夏の恒例行事となる。牛頭天王を祀る八坂神社の祭礼、すなわち「祇園祭」の始まりである。

    京都では市民の信仰や伝統行事の中に、疫病と戦った千年以上も前の先人たちの記憶が刻まれている。多くの人を集める祭礼の由来を学ぶことで、私たちは過去に生きた人々の経験を共有し、彼らの苦難に思いをはせ、時空を超えて共感することができる。

    何度も戦火で焼き尽くされた都市

    京都はさまざまな疫病や災害を克服しつつ、長らく日本文化の中心地という役割を担ってきた。この都市の歴史を、その始まりにまでさかのぼろう。

    桓武天皇が長岡京からの遷都の詔（みことのり）を発したのは794（延暦13）年のことだ。新しい都は、中国の長安や洛陽などの都城を手本として計画された。幅員約84メートルの朱雀大路(しゅじゃくおおじ)を南北軸として、左右対称に格子状の街路網を整える。その北端に御所と官庁街を含む「大内裏（だいだいり」を建設した。南端には羅城門（らじょうもん）を置き、その近傍に東寺、西寺の伽藍（がらん）を建立した。市街地は、40丈（約120メートル）を四辺とする「町」を単位として構成。人々の生活を支える物品の流通を図るべく、東市、西市の市場が設置された。

    新しい都は「平安京」と命名された。一説にこの都は、中国から伝来した風水に基づき、四方を霊獣に守護されている「四神相応」の地に建設されたという。すなわち北にある船岡山を空想上の霊獣である「玄武」にたとえ、東辺を流れるように改修した鴨川を「青龍（せいりょう）」、西に伸びる大道である山陰道を「白虎（びゃっこ）」、南に水をたたえた巨椋池(おぐらいけ)を「朱雀」に見立てて、その中心に都を築いたのである。

    平安京の名称には「平らかで安らか」、すなわち平和な世が継続してほしいという思いが託されている。しかしその名に反して、しばしば戦火に焼かれた。1467年から77年まで続いた応仁の乱にあっては、市街地が主な戦場になる。その後、16世紀末には天下統一を進めていた豊臣秀吉によって、聚楽第（じゅらくだい）と称した居城を中心とする城塞（じょうさい）都市への改造が行われ、寺院街の再編も断行された。この時に整備された市街地が、今日の京都の原型となる。

    近世には幾度もの大火に見舞われた。1788年の「天明の大火」では、二昼夜にわたって市街地が紅蓮（ぐれん）の炎に包まれた。さらに1864年に勃発した「禁門の変」では、長州藩と会津藩との武力衝突の中で兵が放った火が市街地に燃え広がり、3万戸が消失した。

    戦火や災害に遭い、そのたびごとに復興し、都市はその姿を改めてきた。その結果、1869（明治2年）に東京奠都（てんと）が行われるまで、1100年にわたって日本の首都であり続けた。武家によって統治された幕府が遠く東国の鎌倉や江戸に移された時代にも御所はこの街に置かれ、日本の政治的な中心という地位を保ち続ける。

    人々は「平安京」をいつからか「京」の一文字で記し、「みやこ」と呼ぶようになった。誰もが日本で唯一の政治的、文化的な中心地であることを信じて疑わなかったのだろう。

    歴史的文化財の宝庫

    京の都では、さまざまな文化が生まれた。公家や武家の儀礼に由来する文化、さらには庶民によって育まれた生活文化など、その豊かさ、多様さと洗練の度合いは世界でも稀（まれ）なものだ。

    もっとも市街地の中心部は幾度もの火災で焼かれたため、ここで生まれた文化的所産の精華は、京都市の郊外にこそ見いだされる。各時代の支配者が建てた別業（なりどころ＝貴族の別荘）、離宮や寺院などは周縁部に点在し、建築や庭園の造作、仏教彫刻や障壁画などの美術に加えて、茶道や華道などの芸術に至るまで、各時代の栄華の名残を今日に伝えている。

    古代に渡来した人々の活動拠点となった太秦（うずまさ）には弥勒菩薩像で知られる広隆寺があり、嵯峨野には嵯峨天皇の離宮を改めた大覚寺がある。現在、文化施設が集積している岡崎は、白河天皇が建立した法勝寺に代表される寺院群に由来する。

    宇治には、中国文化を日本独自の文化に昇華させた「国風文化」の象徴である平等院鳳凰堂（ほうおうどう）がある。優雅な建築様式を備え、日野薬師として知られる法界寺阿弥陀堂とともに、末法思想が流行した平安時代末期に、いかに貴族たちが阿弥陀信仰に熱心であったかを知ることができる。

    室町時代になると、3代将軍足利義満は武家文化と公家文化の融合を図り、「北山文化」を開花させた。池に美しい姿を映す鹿苑寺（ろくおんじ）金閣は、伝統的な住宅様式であった寝殿造りと、新たに渡来した禅宗の寺院建築様式を折衷したものだ。

    それに対して8代将軍足利義政による「東山文化」の象徴が慈照寺銀閣である。回遊式の庭園には、書院造の原型を示す東求堂（とうぐどう）などがある。また曼殊院（まんじゅいん）、桂離宮（かつらりきゅう）、修学院離宮など、数寄屋建築の神髄も京都の周辺部に数多く残されている。

    京で暮らす人たちは、おおむね秀吉が城塞に改造した市街地を、平安京が範にとった「洛陽」にちなんで「洛中（らくちゅう）」と呼び、その外部に広がる田園や近郊の山々までを「洛外（らくがい）」と称した。「洛中洛外」の四文字で、町家が集まる市街地と、豊かな田園の双方、すなわち京都の地理的な全体像を意味することができる。

    先人たちはどの時代にあっても、外来文化を常に和風に改め、日本独自のものとして受容してきた。さまざまな文化を混合し、折衷し、新奇なものを創造しつつ、時間の経過を経て、それを京都の伝統という文脈に取り込んできた。各時代の歴史的・文化的営為が「洛中洛外」と総称される空間と時間の中にふんだんに埋め込まれている（後編に続く）。

    バナー写真＝室町時代の京都の市中とその郊外の名所などが俯瞰（ふかん）的に描かれた洛中洛外図（アフロ)

------------------------------------------------------------------------

### 日本:オノマトペ

**[日本語再発見（1）オノマトペの不思議な世界](https://www.nippon.com/ja/views/b05602/?cx_recs_click=true)**


    オノマトペが豊富な日本語

    「ゴロゴロしていないで、子どもの面倒を見なさい」「ダラダラ電話しないで！」「ウロウロしないで！」。こんな家人の声を聞くと、僕は決まって「ビクビク」する。――こんな夫婦の様子に限らず、状況の細かいニュアンスを上手く描写してくれるのが「ゴロゴロ」「ビクビク」といったオノマトペである

    オノマトペとは、状態や感情、あるいは動物の鳴き声や物音を、模倣したものであり、その中には「擬音語」と「擬態語」がある。「擬音語」とは、物音や動物の鳴き声など、人間の発声器官以外のものから出た音を、人間の音声で模倣したものである。

    もう一つの「擬態語」の語彙（ごい）が豊富であることが、日本語の大きな特徴の一つである。これは、日本語を当たり前に使っている人々にとっては体にしみついたごく普通の表現である。もちろん世界中の言語にはオノマトペがあるが、それに対する音感覚は言語によってかなり違ってくる。

    日本語のオノマトペ：一例とその主な意味

    イライラ  
    草木のとげのことをいう「イラ」に由来。不快で落ち着きを失ってるような状態を指す 
    例文： 試験勉強が思うように進まずイライラする。

    ピカピカ   
    光沢、つやがあるさま 
    例文：靴をピカピカに磨いて会社に行く。

    ワクワク   
    水が地中から「わく」様子が語源とされる。期待や喜びなどで気持ちが高ぶるさま 
    例文：恋人が留学を終え、帰ってくる。ワクワクしながら空港に迎えに行った。

    フワフワ    
    ふっくらとして軽いさま、またその軽いものが浮いてただよう様子 
    例文：青空に白い雲がフワフワ浮いている。

    モチモチ   
    1. 粘りけがある食物の柔らかい食感　  
    2. 肌がふっくらとして張りがあるさま   
    例文：赤ちゃんのモチモチした肌がうらやましい。

    ニコニコ   
    楽しそうな微笑みを浮かべた笑顔 
    例文：何かいいことがあったのか、今日の上司は終始ニコニコ顔だ。

    ペコペコ   
    空腹な様子。人にへつらう様子。「へこむ」が変化して重なったのが語源との説も 
    例文：お腹がペコペコで集中できない。社長にペコペコする。

    ドキドキ   
    喜び、不安、恐怖、驚きなどで心臓が高鳴る様子 
    例文：試験結果発表の日、不安で心臓がドキドキする

    ペラペラ   
    よどみなくしゃべるさま、特に外国語に長けていること。
    彼は英語がペラペラだ。

    「鳴き声」はオノマトペで使い分け  

    日本語は、アラビア語や英語に比べれば動詞と形容詞が少ない言語であり、カラス、小鳥、犬、ネコ、羊、カエル、虫などが「なく」場合、みんな「鳴く」という表現しかない。その代わりそれぞれの鳥や動物が副詞の擬音で鳴くと表現する。例えば、カラスはカーカーと、小鳥はチュンチュンと、犬はワンワンと鳴く。漢字が豊富にあるから「鳴く」「啼く」「哭く」と使い分けすることで動詞が発展しなかったとも説明できる。

    また、笑い方や歩き方、食べ方などを表す擬態語、擬音語が日本語の中には圧倒的に多い。例えば、笑い方を表すオノマトペには「ケラケラ」「ゲラゲラ」「クスクス」「ニヤニヤ」「ニコニコ」「ニタニタ」などがある。

    しかし、アラビア語や英語などのような言語では、それぞれの鳥や動物が個別に動詞で鳴く。例えば、英語では犬が「なく」場合は“Bark”、ライオンが「なく」場合は“Roar”、カエルが「なく」場合は“Croak”となるわけである。アラビア語も同様である。要するに日本語で例えると「囀（さえず）る」や「吠える」や「嘶（いなな）く」などといったものであろう。

    1つで複数の意味があるオノマトペも

    ゴロゴロ  
    ①雷の音   
    例文：雷がゴロゴロと鳴っている。

    ②大きく重いものが転がるさま   
    例文：岩がゴロゴロと転がり落ちていった。  

    ③目に異物が入ったり、腹の調子が悪い様子   
    例文：牛乳を飲んだらおなかがゴロゴロしてきた。  

    ④ありふれた例であること   
    例文：そんな話は世間にゴロゴロしている。  

    ⑤暇を持て余している様子  
    例文：休みの日は家でゴロゴロしている。  

    痛みの種類を的確に伝達

    日本語では痛みを表す表現として、「キリキリ」「ズキズキ」「ピリピリ」「ジンジン」「ズキンズキン」「ビリビリ」「チクチク」「ガンガン」といった、さまざまなオノマトペがある。

    痛みの種類とその表現を把握することは、実際に痛みを説明したり、理解させたりする際に大変役に立つ。 例えば「とがったもので刺すような痛みが何度も襲ってくる」と言わなくとも、「キリキリ痛む」と言えば十分に医師や相手に伝わる。私の場合、まだまだ日本語のオノマトペの語彙が十分でないため、胃が痛くて苦しい時にさらに苦しくなる。しかしオノマトペを使えば、表現にそんなに苦しまなくてもいいのである。

    そう考えれば、オノマトペをもっと有効に活用していった方が、はるかに円滑なコミュニケーションが可能になる。そんな独特な世界を作るオノマトペが好きで、これからもドンドン使っていきたい。

    バナーと文中漫画＝モクタン・アンジェロ

------------------------------------------------------------------------

### 鉄道絶景

**[鉄道絶景：列車と自然が織りなす日本の春夏秋冬](https://www.nippon.com/ja/images/i00055/?cx_recs_click=true)**

    鉄道写真を撮影するために全国を駆け巡っていて思うのは、日本は実に美しい国だということだ。雄大な自然と鉄道が織りなす絶景が全国各所に点在している。山や川、海などの自然だけでなく、その土地に暮らす人々の営みを感じさせる街並みなど、四季折々の絶妙なグラデーションが創り出すきめ細やかな「彩り」を目の前に見せてくれる。

    四季の移ろいを感じながら列車を待つ至福の時間

    青空のもと満開に咲き誇る桜と列車のコラボレーションは、晴れやかで気持ちのいい「鉄道風景写真」となる。雨や霧の日に見せる妖美な桜も捨てがたく、列車のヘッドライトや窓明かりを写し込むことでより幻想的な写真になる。満開の桜は格別だが、「花吹雪」や「花筏（はないかだ）」と表される散りゆく姿もいい。天候と時間帯、光線を変えて捉えられた桜と列車を組み合わせることで、さまざまな鉄道春景が生まれる。

    桜の季節が終わり新緑のシーズンが訪れると、木々が微妙な色合いのグラデーションで芽吹き始める。まさに「山笑う」季節。そんなのどかな景色にカメラを向けて列車がやってくるのを待っていると、思わず「花鳥風月」という言葉が浮かんでくる。そしてどこからともなく「ホーホケキョ」と、春告げ鳥と呼ばれる鶯（うぐいす）の鳴き声が聴こえてくる。そんなひと時が私にとっては至福の時間だ。

    秋には錦繍（きんしゅう）に輝く紅葉に目を奪われ、冬には一面銀世界の中でじっと列車の訪れを待つ。艶(あで)やかな彩りや静謐（せいひつ）なモノトーンの中に飛び込んでくる列車の姿を想像する。今度はどんな鉄道絶景に出会えるだろうか。力まず淡々と、季節の風を感じながら、そんなことを思いながら私はいつもカメラを構えている。

    まだ出会えぬ鉄道絶景を求めて

    鉄道は街と街を結び、その地方の文化と文化を結ぶ。そこには、出会いと別れ、喜びと悲しみ、憧れと郷愁などが幾重にも重ねられた思いが交差する。そうした鉄道という役者に彩り豊かな四季折々の風景が加われば、最高の舞台が出来上がる。

    「ガタンゴトン」と心地よいリズムに身を任せ、移りゆく車窓を眺めていると、不思議と心が和んでくる。日常生活の中で、何気なく耳にする踏切の音や、どこまでも続く鉄路の先にふと忘れかけていた懐かしい思いがよみがえってくる。「鉄道」だけがもつ移動速度と律動が、あわただしい時間の合間にホッとさせてくれる安堵（あんど）を私たちにもたらしてくれるのかもしれない。

    まだまだ、出会えたことのない自然が織りなす鉄道絶景は無限にある。さまざまな好条件が重なり合う奇跡的な瞬間を逃さないためにも、出会った光景としっかりと向き合い、その一期一会の瞬間を大切に、季節の風や音、匂いを五感で感じて撮影に挑み続けていきたい。

    JR中央本線の新府（しんぷ）〜穴山間（山梨県韮崎市）を走るE353系あずさ。4月。富士山、八ヶ岳、南アルプスと日本の名山を車窓に眺めながら、この季節には桃のピンクの海が目を楽しませてくれる。富士山をバックに桃源郷を疾走する姿をカメラに収めた。

    JR中央本線の落合川〜中津川間（岐阜県中津川市）を走る313系。4月。撮影場所を探すときには、鉄道と四季の風景・時間帯をどう組み合わせて撮ろうかと思案しながら車を走らせる。中津川市の何気ない山あいの里に一本桜を見つけた時、春の野を列車が駆けるこの風景に出会った。

    JR八戸線の鮫（さめ）〜陸奥白浜間（青森県八戸市）を走るE130系。5月。太平洋を一望できる鮫角（さめかど）灯台より撮影。4月から10月まで灯台に登れるので、牧歌的な風景の中をのどかに走りゆく列車の姿を捉えることができる。

    JR奥羽本線の庭坂〜赤岩間（福島県福島市）を走る山形新幹線E3系つばさ。5月。吾妻連峰の麓を走るこの区間は、沿線に桃や梨の花が咲き誇るフルーツラインだ。つばさは板谷峠を越え、一路山形へと向かう

    JR田沢湖線の赤渕〜田沢湖間（岩手県雫石町・秋田県仙北市）を走る秋田新幹線E6系こまち。6月。新幹線は高速で都市間を結ぶ。しかし秋田新幹線と山形新幹線は幹線を離れ、標準軌の1435ミリに改良された奥羽本線と田沢湖線を走る。新緑に包まれた山あいを走り抜ける新幹線もまた格別だ。

    JR東海道新幹線の三島〜新富士間（静岡県三島市・富士市）を走るN700Aのぞみ。7月。この区間には富士山と新幹線を撮影できる絶好の撮影ポイントが各所にある。幻想的な夕日に包まれておぼろげに浮かび上がる富士山の麓で、上りと下りの新幹線が出会った。

    JR姫新線の播磨徳久（はりまとくさ）〜三日月間（兵庫県佐用町）を走るキハ127系気動車。7月。佐用町のひまわり畑は有名で、昼間は見物客も多くアングル探しに苦労するので、人の少ない朝夕の時間帯を選んだ。太陽が沈むぎりぎりの時間に列車が姿を見せてくれた。

    JR久大本線（きゅうだいほんせん）の由布院〜南由布間（大分県由布市）を走るキハ200系気動車。8月。気動車は内燃機関をもつ列車で、電線がなくスッキリと写真が撮れるのがうれしい。由布院のランドマークである由布岳を背景に朝靄の中、赤い気動車が爽やかに快走する。

    JR山陰本線の折居（おりい）〜三保三隅間（島根県浜田市）を走るキハ120形気動車。8月。澄み渡った青空と鮮やかなブルーが印象的な日本海を背景にして走り抜けていく様に、爽やかな涼風を感じた。まるで海の上に線路があるかのようだ。

    JR陸羽東線（りくうとうせん）の鳴子温泉〜中山平温泉間（宮城県大崎市）を走るキハ110系気動車。10月。鳴子侠は東北でも指折りの紅葉スッポット。錦繍に彩られた峡谷に列車が現れると、思わず息をのむ。ちょうど霧が立ち込めてきて、まるで夢の中の光景のようだ。

    JR瀬戸大橋線の児島〜坂出（さかいで）間（岡山県倉敷市・香川県坂出市）を走る5000系マリンライナー。10月。1988年に瀬戸大橋が開通して以来、橋を渡る列車と夕日のコラボレーションは多くの鉄道ファンを魅了してきた。四国側から、夕日に向かって走る列車のシルエットを捉えた。

    JR陸羽東線の上野目（かみのめ）〜池月（いけづき）間（宮城県大崎市）を走るキハ110系気動車。1月。日が昇ったばかりのマジックアワーは、神話的な時間帯だ。この日も薄明の中を走る姿を求めて車中泊。モーニングコーヒーを飲みながら待っていると、始発列車が現れた。

    JR只見線の会津川口駅（福島県金山町）で、出発を待つキハ40形気動車。1月。この辺りは日本屈指の豪雪地帯。2011年の新潟・福島豪雨のため会津川口〜只見間は不通になっていて、全線開通にはしばらく時間がかかりそうだ。現在、この秘境ラインにはキハE120形気動車が運行している。

    JR釧路本線の止別〜知床斜里間（北海道斜里町）を走るキハ54形気動車。2月。オホーツク海の流氷が接岸したのを確認して、撮影に向かった。左側に見えるのは流氷だが、接岸すると雪原と見分けがつかなくなる

    JR津軽線の三厩（みんまや）駅（青森県外ケ浜町）に停車するキハ40系気動車。2月。三厩駅は、JR東日本最北端の終着駅。雪原に自分の足跡を残さないよう目指す撮影ポイントまで遠回りした。現在は新型車両のGV-E400系が運行している。

    JR田沢湖線の角館〜鶯野（うぐいすの）間（秋田県仙北市）を走る秋田新幹線E6系こまち。2月。雪原を走り抜けるこまちが撮れないかと車で農道に入ったら、地元の親子が楽しそうに飛来した白鳥を見ていた。近所の農家が餌付けしているという話を聞きながら、シャッターを切った。

    JR根室本線の厚岸（あっけし）〜糸魚沢（いといざわ）間（北海道厚岸町）を走るキハ54形気動車。3月。北海道では、本州の撮影より1.5倍ほど長いレンズがほしくなる。「北海道は広いなあ」と思いながら待っていると、別寒辺牛（べかんべうし）湿原を横断する列車がやって来た。

    写真と文＝猪井 貴志

    バナー写真＝JR室蘭本線の伊達紋別〜北舟岡間（北海道伊達市）を走る豪華寝台特急「カシオペア」。9月。1999年から上野〜札幌間（東京都・北海道）を走ったが、2016年の北海道新幹線開業によりE5系新幹線に受け継がれた。

------------------------------------------------------------------------

### 豚骨ラーメン:一蘭

**[台湾に「博多の魂」豚骨ラーメンを広めた「一蘭」――人気の秘密を分析する](https://www.nippon.com/ja/japan-topics/c09802/)**

    行列の連続記録は312時間

    台北市の東部の信義区は、1990年代に急速に成長した新開発エリアだ。商業ビルが林立し、高級レストランが軒を連ね、夜になると六本木のような魅惑的な街となる。その一角に昼夜を問わず行列ができる店がある。福岡・博多発のラーメン店「一蘭」だ。コロナ禍にあっても、その人気が陰る様子はない。

    一蘭の台湾1号店がオープンしたのは、2017年６月15日。初日から長蛇の列ができ、その光景には日本の本社も相当驚いたという。「行列の連続記録は312時間です。その間、一度も途切れなかったのですよ」と、話すのは一蘭の台湾支社・広報担当の林宛瑩（りん・えんえい）さんだ。

    長蛇の列を緩和しようと、18年6月にはわずか300メートルの場所に2号店をオープンさせた。林さんによると2店舗体制になった後も、行列はなくならず、平日でも2〜3時間待ち、休日は5〜6時間待たなければならないほどだったという。

    2020年に入って新型コロナウイルスの流行で、一時的に客足が遠のいた時期もあったが、台湾で感染拡大の抑え込みの効果が出てくると、客は徐々に戻ってきたそうだ。

    一蘭は台湾人にとって日本のラーメン店の中で最も人気がある店になった。しかし九州の豚骨味がなぜこうも台湾で人気を得たのだろうか？　それは台湾の食文化と大きな関係があると言えそうだ。

    豚肉好きの台湾人と福岡人

    台湾グルメと言えば、滷肉飯（ルーローハン）と牛肉麺が代表格だが、牛肉麺は、第二次世界大戦後に外省人（戦後、蒋介石と共に中国大陸から移住してきた人達）によって考案されたものだ。一方、滷肉飯は、豚バラ肉を甘辛いたれで柔らかく煮込んでご飯にかけたもので、台湾発祥の食べ物である。他の台湾料理を見ても、切仔麵、陽春麵、初期の猪油拌飯などいずれも豚肉をメインにする料理で、台湾の食文化に豚肉は不可欠なのだ。

    同様に、名物の豚骨ラーメンとモツ鍋に象徴されるように、福岡も豚肉文化圏と言える。筆者は2008年に福岡に留学したのだが、初めて豚骨ラーメンを食べたとき、昔から知っている懐かしい味のように感じた。そこから筆者の「豚骨ラーメン巡礼」が始まった。留学期間中の1年に30軒以上のラーメン店を巡り、一蘭に至っては週に2度行くこともあった。

    台湾一蘭の広報・林さんはこう語る。

    「豚骨スープが台湾で広く受け入れられたのは、台湾人が鶏や豚などを使ったスープを好むことにも関係があると考えられます。昔から台湾では濃厚な鶏スープが食されてきたこともあり、あっさりした醤油ラーメンよりも、こってりした豚骨スープの方が台湾人好みなのです」

    福岡の豚骨ラーメンは「久留米系」と「長浜系」に分けることができ、それぞれに違った特徴がある。老舗のラーメン店に入ると、長年熟成されたような濃厚な豚骨スープの香りが鼻をつき、かつては白かったであろう壁に豚骨のエキスがしみ込んで黄色く変色している。地元の豚骨好きにとってはそれが当たり前のことであっても、女性客や他の地方からの客なら、この強烈な臭いに引いてしまうかもしれない。

    一蘭の店舗は清掃と換気を徹底することで、豚骨特有の臭いの問題を改善し、さらに味も大衆に受け入れられやすいよう改良した。こうして一蘭は福岡から日本全国へと展開。筆者が留学していた頃、一蘭の店舗は日本で20店に満たなかったが、現在は85店舗を数え、世界進出も果たした。香港、ニューヨーク、そして17年に台湾に進出し、一蘭独自の風味を現地に広めていったのだ。

    元祖ソーシャルディスタンスと替玉文化

    一蘭の店舗の最大の特徴は、席1つ1つを板で仕切った「味集中カウンター」だ。周囲の目を気にせずラーメンを味わうことだけに集中できる席で、日本でも類を見ないオリジナルのシステムだ。台湾店オープンの際には、台湾人に大きなインパクトを与え、林さんは、客から「なんだか自習室みたいですね」と言われたこともあるという。カウンター上にあるセルフ給水器の蛇口に荷物を引っ掛けてしまう客もいたという。

    林さんは「日本では1人で来店されるお客様が多いのに、台湾では2〜3人で来られる方が多いですね」と話す。台湾ではラーメンをグループで食べることが好まれるため、当初はカウンターに分かれて座ることで、おしゃべりできないことへの不満の声も聞かれたそうだ。

    しかし、世界中で新型コロナウイルスが猛威を奮うようになってからというもの、食事中の会話はできなくなり、台湾人も一蘭のスタイルになじんでいった。コロナ禍以降は、あちこちの飲食店が飛沫防止のアクリル板を設置するようになったが、25年以上前に味集中カウンターを生み出した一蘭は、まさかの「ソーシャルディスタンスの元祖」になったのだ。

    スープを残して麺だけをおかわりする博多独自の「替玉」文化も、一蘭の台湾進出当初は台湾人にとって未知のものだった。筆者が留学で福岡に暮らし始めて間もないころ、ラーメンを注文するのと同時に替玉を頼んで、店員に「替玉は食べ終わった後ですよ」と笑われたことがあった。

    台湾でも一蘭の替玉システムが定着するのには時間が必要だった。林さんによると、当初はスープを全て飲み干してから替玉を注文する客もいて、スープのおかわりができないことに相当がっかりされたそうだ。

    一蘭では替玉を注文する際には、各席に設置された呼び出しボタンの上に、専用の替え玉プレートを置く。するとチャルメラが流れ、注文の受付が完了する。台湾の一蘭では店のシステムを説明したポスターを作成、座席に貼ることで客に周知した。

    本社の品質へのこだわりと管理体制

    海を越えてやってきた台湾で、一蘭のラーメンの価格は台湾人を驚かせた。そもそも一蘭は日本でもラーメンとしては高価格帯店に分類されるが、台湾での値段は1杯300台湾ドル（約1200円）近くで、台湾ではちょっとした西洋料理が食べられる値段だ。

    林さんは価格に対する台湾人の考えは理解できるとした上で、「毎日スープを日本から直送しているため、原価が高めなのです」と説明する。また、一蘭では厳しい品質管理体制をとっている。本店と同じ味を提供するため、各店舗では送られてきたスープには水を加えることをはじめ、いかなる加工も許されていない。加熱した後に出る水蒸気ですら逃してはならないのだ。水蒸気もスープの一部であると考えられているためだ。これは日本のどの店舗も同様である。

    一蘭のこだわりはオリジナルの味を守ること以外に、立地にもある。林さんはこう話す。「当初、西門町、永康街、東区などの繁華街への出店も検討しましたが、差別化を図るため、最終的に信義区を選んだのです」。それは欧米のレストランが日本へ進出する際に1号店を六本木や銀座にオープンさせる感覚に似ているのだという。

    「台湾のお客様はレストランに来るような感覚でいらっしゃいます」と話すのは、もう1人の広報担当・蒋怡璉（しょう・いれん）さんだ。日本では、ラーメンは手っ取り早くエネルギーを補給するファストフードのようなものだが、林さんによると、台湾人にとってラーメンを食べに行くのは、デートコースにもなるそうで、食べながらおしゃべりを楽しみたいものなのだという。

    コロナ禍でも収益を伸ばす台湾の一蘭

    2017年に台湾1号店がオープンして以来、一蘭は台湾で目を見張るほどの業績を上げている。オープン2年で、のべ150万人が来店、21年2月の段階では、その数は350万人に迫っている。

    「豚骨ラーメンが台湾で受け入れられたことが喜ばしく、日本側からも一蘭・台湾店は高く評価されています」

    他のラーメン店と異なり、一蘭は「ラーメン1本勝負」の店だ。たった1種類のラーメンが、台湾人の心をしっかりとつかんだのだ。一蘭のニューヨーク支店は新型コロナウイルス流行の影響を受け、香港支店では香港民主化デモ後、業績が下降している。比較的、感染の拡大の抑制に成功し、政治的な不安がない台湾は、日本にとって新しい重要な市場になるのではないだろうか。

    広報の林さんは、現在、一蘭では新北市、台中市、台南市、高雄市等の台北以外のエリアへの出店を積極的に検討していると明かした。一蘭が台湾の他の地方へ出店するとなれば、現地で豚骨ラーメンと一蘭のシステムを広めていくのは台湾支社の仕事だ。林さんは「私たちは、毎日キャッチコピーや宣伝方法を考えています」と笑みをこぼす。

    福岡人はラーメンには硬めに茹でた麺・カタ麺を好み、中でも最も硬いものは「バリカタ」と呼ばれる。台湾で一般的な硬さの麺に慣れた客は、更なるカタ麺へとチャレンジし、ラーメンを楽しんだ後は、お土産を買い、家族や友人に贈る。これは一蘭が台湾で豚骨ラーメンを広めてから台湾人の間で知らず知らずのうちに定着した文化である。

    「信義区に来たら一蘭、台湾で豚骨ラーメンと言えば一蘭、そうなってほしいと思っています」

    林さんは今後の目標についてこう語った。異郷の地・台湾で並々ならぬ成功を収めた福岡グルメ。彼らはその胸に今後5年間を見据えた長期的な野心を抱いている。

    バナー写真＝2020年のコロナ禍でも業績が好調だった一覧の台湾1号店（筆者撮影）
    
------------------------------------------------------------------------

### ポッドキャスト {.tabset}

#### 日本語-スイッチ {.tabset}

##### 六十五

**[JAPANESE DILEMMA WITH KATAKANA-KOTOBA](https://nihongoswitch.com/podcast-transcripts/ep65-katakana-kotoba)**

    こんにちは。お元気ですか。日本語スイッチの郁(いく)です。日本語の勉強を楽しんでいますか。 
    
    今日はカタカナで書かれる言葉、カタカナ言葉について話したいと思います。みんな大好きカタカナ言葉。(なんてね。すみません、じょうだんです。)「え、やめて～。聞きたくない」という人は多いと思います。確かに嫌われ者ですよね。読みにくい、分かりにくい、ていうか、意味わからんモノもありますからね。

    さて、カタカナ言葉と言えば外来語、海外から来た言葉が多いですよね。たとえば、コーヒーとかTシャツとかね。現代の日本人は、毎日たくさんのカタカナ言葉を使っています。もうカタカナ言葉なしでは、生きられない。スムーズに会話ができないくらいなんです。
    
    たとえば、「朝、アラームで起きて、すぐシャワーを浴びて、近くのカフェでモーニング・セットを食べた」みたいにね。もちろん、「朝、目覚まし時計で起きて、すぐひとっぷろ浴びて、近くの喫茶店で朝ごはん定食を食べた」とも言えるんですけどね。カタカナ言葉は、何気にたくさん使っちゃうんですよね。
    
    日本人の間でも、「最近の日本人はカタカナ言葉を使いすぎだよね。困ったものだ」と感じている人が多いんです。「その言葉、日本語のままでいいんじゃない?　なんで、わざわざ外来語を使うのかな。ふつうの日本語で話してよ」てね。
    
    そこで、今日は日本人が使いがちなカタカナ言葉、「スムーズ。トイレ。フリー。チェックする」の四つを、前からある日本語に直してみたいと思います。できるかな～。まあ、つべこべ言わないでやってみますね。あなたも一緒に、カタカナ言葉の言い換えを考えてみてください。

    頭の中の日本語のスイッチを入れて、最後まで聞いてくださいね。
    さあ、一つ目は、さっき私が言った「スムーズに会話ができない」の「スムーズ。」文の内容によって、いろいろな言葉で言えるんですよ。会話文で紹介しましょう。たとえば、友だちの家に初めて行ったとき…。

    Aさん：ここまで、スムーズに来れた?　/　ここまで、問題なく来れた?

    Bさん：うん、スムーズだったよ。　/　うん、問題なかったよ。

    「スムーズだ」を、「問題ない」と言い換えました。次は、スムーズを「うまく行く」と言い換えます。会社で。

    Aさん:　この間の会議はスムーズでしたね。/　この間の会議は、うまくいきましたね。

    つぎは、「スムーズに」を「間違えずに」や「すらすら」で言ってみますよ。学校で。

    先生:　49ページを声に出して読みましょう。…はい、みなさん、スムーズに読めましたね。/　はい、みなさん、間違えずに読めましたね。/はい、みなさん、すらすら読めましたね。

    つぎは、「なめらか」で表現します。洋服屋さんで。

    店員：この服はいかがですか。ちょっと触ってみてください。すごくスムーズでしょう。/　すごくなめらかでしょう。

    同じ「スムーズ」でも話の内容によって、使う言葉が変わるんですね。逆に言うと、複数の言い方を「スムーズ」一つで言えるんですから、なんとも便利なカタカナ言葉です。

    次は、誰でも毎日使う「トイレ。」トイレは、別の言葉で何て言えるでしょうか?　もし、あなたが「厠(かわや)」や「ご不浄(ふじょう)」「はばかり」と習ったなら、今すぐその教科書を捨ててください。古すぎます。「便所(べんじょ)」という言葉も、もうほとんど使わないですね。「便所」にはちょっと汚いイメージがあるので、あまり使われません。「トイレ」以外で、一般的によく使われるのは、「お手洗い」です。「お手洗い」は文字通り、手を洗う場所という意味です。たとえば、こんな風に言いますよ。

    •	(デパートやレストランで)「すみません、お手洗いはどこですか。」

    •	(知り合いの家で)「お手洗いをお借りしてもいいですか。」　誰かの家でトイレを使う場合は、「借りる」という動詞を使います。お手洗いを借りる。

    では、次。

    •	(友達の家で)お手洗いを使ってもいい?　(気楽な関係なら、「お手洗いを借りる」じゃなくて、「お手洗いを使う」でもいいですよ。)

    お手洗い＝トイレのように、前からある日本語の言葉と新しいカタカナ言葉の両方使われている例はたくさんあります。思いつくまま言ってみますね。ローション＝化粧水、ヘア・スタイル＝髪型、ヘア・サロン＝美容院、キッチン＝台所、エントランス＝玄関、入口。クリニック＝医院、ランチ＝昼ごはん・昼食、モバイル＝携帯(けいたい)、パーティ・ピーポー(party people)、パリピ＝遊び人、インフォメーション＝情報などなど。きりがありません。

    じゃあ、どうして昔からある言葉をわざわざカタカナ言葉にするのか。これは、私の個人的な意見ですけど、カタカナ言葉には新しい、おしゃれというイメージがあるんです。以前日本に海外からいろいろなものや考え方が入ってきたときに、外来語というものが生まれて、当時の日本人は外来語を使っている人は新しいことを知っている人、おしゃれな人というイメージを持つようになったんです。そこに目をつけたのがビジネスをする人たち。新しくて、おしゃれというイメージをつけるためにいろいろな言葉をカタカナ言葉に変えて言い始めたのが、広まったんだと思います。たしかに、「喫茶店」よりは「カフェ」の方が、「雑誌」よりは「マガジン」の方がなんかおしゃれっぽいですもんね。でも、最近は反動で、漢字だけの古い言葉の方がおしゃれに感じる人も増えてきている気がしますけどね。

    じゃあ、話を戻しますね。三番目は、マーケター(marketer) がよく使う、「フリー。」町にも、インターネットにも、「フリー」の文字が日本にはあふれています。「自由、無料、タダ」と言い換えることができます。たとえば、ホテルの受付に町の地図が置いてありました。

    受付の人：こちらの地図は無料ですので、ご自由にお持ちください。

    お客さんA：えっ、これフリーなの?　ねえ、Bさんこれ、タダだって。

    お客さんB：えっ、これ無料なの。じゃあ、私も一枚もらおうかな。

    ちなみに、無料の反対は、「有料(ゆうりょう)。」「有料」と書いてあったら、お金がかかりますので、気をつけてくださいね。たとえば、さっきのホテルの受付で。

    Aさん：すみません。東京駅までのシャトルバスは無料ですか。

    受付の人：いいえ、シャトルバスは有料なんです。東京駅までだと２００円です。

    さて、「フリー」には「フリーランス・フリーランサー」という意味もあります。つまり、会社に属しているのではなくて、個人で仕事をしている人のことですね。たとえば、

    Aさん：先日、会社を辞めて、フリーのプログラマーになったんです。

    Bさん：そうなんですか。私は、フリーのウエブデザイナーなんです。一緒にお仕事ができるといいですね。

    フリーのプログラマー、フリーのデザイナーと言っても、タダで働くわけじゃないですからね、ご注意ください。

    もう一つ、「フリー」には、決まった恋人がいないという意味もあります。たとえば、

    Aさん：この間、恋人と別れてさ。今、フリーなんだ。誰かいい人いないかな～。

    Bさん：あ、そうなの。今、付き合っている人はいないんだ。じゃあさ、毎日飲みに行けるじゃん。

    Aさん：いやだよ。お前とつるんでたら、一生恋人ができないよ。

    ちなみに、「つるむ」というのはいつも一緒にいるという意味です。どちらかというと悪友(あくゆう)、いつでもどこに行くのもいっしょ。一緒にばかばかしいことをやっている友達のイメージかな。あなたには、いつもつるんでいる人はいますか。

    さあ、では最後は、「チェックする。」英語のcheckにはいろいろな意味がありますが、カタカナ言葉の場合はだいたい「確認する」か「調べる」という意味で使われています。たとえば、

    •	すみません。この漢字が間違っていないかチェックしてもらえませんか。/　この漢字が間違っていないか確認してもらえませんか。

    •	明日の天気予報をチェックしてくれる?/　明日の天気予報を調べてくれる?

    まあ、ほかにも

    「この歌すごくいいから、チェックしてみて」だったら、「この歌すごくいいから、聞いてみて」といった感じ。いろいろな言い方ができますね。
    さあ、いかがでしたか。今日は、カタカナ言葉について話しました。

    実は、私はレッスンをしている時に胸がちくちく痛くなることがあるんです。それは、生徒さんのカタカナ言葉の発音を直す時です。マクドナルド、レストラン、サラダ、ハンバーガーなどなど。もともと英語の言葉なのにね、日本語風に発音を覚えなおさなきゃいけないですよね。これ、私が生徒さんだったら、「いったい何の罰(ばつ)ゲーム?　何やってんだろう、私?」って思っちゃうだろうなあと思うんですよね。だって、これって、たとえば、英語の先生が日本人の私に「ノー、It’s sushi. Hara-kiri, Sake, Tofu」みたいに言えっていってるみたいじゃないですか。なんだかね～、納得（なっとく）できないですよね。でも、「ローマではローマ人のようにしなさい」といいますからね。その国の人のように発音しないと通じない、わかってもらえないんだから、しょうがない。ここは割り切って、必要なカタカナ言葉は覚えていきましょう。

    さて、日本語スイッチのホームページ、nihongoswitch.comが変わります。六月からトランスクリプトのページを公開して、だれでも見ることができるようになります。聞いてもわからなかったところを、気軽に確認できるようになりますよ。今度、日本語スイッチのホームページにも遊びに来てもらえると嬉しいです。

    それでは、今週もあなたが日本語を楽しめますように。

    また来週の火曜日に。よい一日を。またね～。

------------------------------------------------------------------------

##### 六十三

**[TALK LIKE A NINJA](https://nihongoswitch.com/transcript)**  

    こんにちは。お元気ですか。日本語スイッチの郁(いく)です。ニンニン! 日本語の勉強を楽しんでいますか。ニンニン!
    さて、あなたはどんな日本文化を知っていますか。アニメ、ゲーム、富士山、舞妓 (まいこ)さん、鮨(すし)、抹茶(まっちゃ)、すもう、村上春樹(むらかみはる き)?     では、忍者は知っていますか。昔日本で、スパイ活動をしていた忍者たち。日 本にも海外にもたくさんのファンがいるんです。
    そういえば、わたしはずーっと前に忍者に間違われたことがあるんです。カナダの大 学で英語の勉強をしていた時のことです。こんなことがありました。休み時間に 2 階 の教室の窓から外を見ていると、下でクラスメートが私に向かって英語でこう叫んでい ました。「忍者、飛べ! 忍者なら、飛べるだろ!飛べ、飛べ、イエ~イ、忍者!」そう言 われて、私は日本人ですからね。もちろん「見てろよ!エイヤッ!」と飛び...ませんでし たよ。「アホか!? ここから飛んだら、死んでしまうわ!」と思って、止めました。あ の日、私は黒い服に髪の毛をポニーテールにしていたので、彼らには私が忍者みたいに 見えたんでしょうね。懐かしい思い出です。
    残念ながら、私は忍者のような運動能力はないんですが、彼らの会話のテクニックに
    ついては話せると思います。忍者の「人の心を動かす会話術」、会話のテクニックを紹
    介したいと思います。ま~、今日はお勉強じゃないので、気楽に聞いてください。
    それでは、頭の中の日本語のスイッチを入れて、最後まで聞いてくださいね。
                   *
    さて、忍者の大切な仕事の中には、情報を集めることがありました。普通の人のふり をして、いろいろな人と会って話をして、情報を集めていたんですね。そういう時、彼

    らは五つの会話テクニックを使っていたそうです。それを「五つの車の術(じゅつ)」と 書いて、「五車(ごしゃ)の術」といいます。「術」とは、技術のことです。カタカナ言 葉で言えば、テクニックですね。「五つの車の術=五車(ごしゃ)の術。」
    なんで車かなあって不思議に思いますよね。日本語には「口車に乗る」という表現が
    あります。「口の車に乗る」誰かの口の車に乗ると言うのは、つまり、誰かの言葉によ
    ってだまされると言う意味なんです。言葉で相手の気持ちを動かす方法、「車」を忍者
    は五つ使っていたんですね。
    まず、一つ目は「喜ぶ車」と書いて、「喜車(きしゃ)の術。」相手を喜ばせるテクニ ック。相手をほめてほめて、喜ばせて、相手の心を開く方法です。たとえば、A さんと B さんが、いっしょにお弁当を食べていますよ。
    A さん:いただきまーす。わあ、B さんのお弁当すごくおいしそう。
    B さん:え、そう? ありがとう。
    A さん:自分で作ったの? すご~い。お店のみたい。
    B さん:えええ、そんなことないよ~。ほとんど昨日の残り物だよ。
    A さん:それでも、すごいよ。ちゃんとお弁当作るなんて、ほんと偉いなあ。その玉子 焼きもきれいにできてるね。
    B さん:玉子焼きは、ちょっと自信があるんだ。一つ食べてみる?
    こんな感じで、A さんは B さんのお弁当をすごくほめましたね。ほめられたら、悪い 気はしません。A さんは、B さんの心を開くことに成功しましたね。人をほめることは 良いことですから、このテクニックは自然に使ってみたいですね。
    
    さて、二つ目は「怒る車」と書いて怒車(どしゃ)の術 。 相手をわざと怒らせるテク ニックです。そして、相手が自分の気持ちのコントロールができなくなるのを待ちま す。ひどいですね、これ。え~、でも相手をわざと怒らせるって、どうやったらいいの かな。難しいですよね。う~ん、そうですね。たとえば、こんな感じの会話はどうでし ょうか。兄弟が家で話しています。お母さんやお父さんは忙しく、夕飯を作っていま す。
    弟:お兄ちゃ~ん、見て見て。また、テストで百点取ったよ。うらやましい? うらやま しいでしょ。お兄ちゃんは、テストで百点取ったことがないよね。頭が悪いと大変だ ね。
    兄:うるさいよ、ばか。 弟:おかあさーん、お兄ちゃんがぼくにバカって言ったー。え~ん(T^T)。 おかあさん:お兄ちゃん!!弟にバカって言ったら、ダメでしょ。         兄:なんだよ、もう。泣きたいのは、オレの方だよ。
    いますね、こういう弟みたいな人。相手をわざと怒らせて、相手をコントロールしよう
    とする人。こういう人がいたら、「あ、怒車の術を使ってるな」って、気をつけましょ
    うね。
    それでは、次。三番目は、「哀しい車」と書いて、哀車(あいしゃ)の術。自分の悲し い話をして、 相手に「かわいそうだなあ。やさしくしてあげよう」と思わせる会話の テクニックです。たとえば、そうですね。さっきの弟がお兄さんのいないところでお母 さんと話していますよ。

    弟:お母さん、お兄ちゃんはね、いつもぼくに「うるさい」とか「バカ」って言うんだよ。
    お母さん:そうなの?
    弟:うん、ぼくはお兄ちゃんのことが大好きなのに...。お兄ちゃんは、僕のことが嫌い
    なんだよ。ぼく、悲しいな。
    お母さん:よしよし。ほら、元気を出して。ママと二人でドーナッツを食べに行こう か!
    弟:わーい。お母さん大好き! この弟は、なかなかやりますね。しっかりお母さんを味方にすることができました。
    しかし、忍者ってすごいですね。何百年も前に心理的なテクニックを使っていたんですね。
    さあ、じゃ四番目の忍者の会話術は、「楽な車」と書いて楽車(らくしゃ)の術。 相 手がうらやましくなるような話をして、相手が戦う気をなくすように仕向けます。たと えば、A        さんは仕事の面接に行きました。たくさんの人が面接の順番を待っています。 自分の番がくるまで、隣の人と話をすることにしました。
    A さん:すごい人の数ですね。こんなにたくさんの人が面接を受けるんだ。ドキドキし てきたなあ。
    B さん:ハハハ。まあまあ、落ち着いて自分らしくしていれば、いいですよ。 A さん:B さんは、落ち着いていますね。失礼ですが、大学はどちらですか。
    
    B さん:私は、東京大学で物理学を勉強しました。その後、ビジネスを学びたくてハー バード大学で MBA を取りました。
    A さん:ぐぐっ。す、すごいですね。
    B さん:その後、そのままアメリカでグーグルで三年、アマゾンで二年働いて...。あ っ、私の番が来ました。では、失礼します。
    A さん:す、すごい人だな。なんだか、他の人もみんなすごい人に見えてきた。彼らに 比べたら、私なんかだめだ。面接を受けても、無駄だよ。もう帰ろう。
    あ~あ、B さんの話のせいで、A さんは面接を受ける前にあきらめちゃいましたね。な るほど、楽車の術も効果的ですね。
    さあ、最後ですね。五番目は、恐ろしい、恐い車と書いて恐車(きょうしゃ)の術。昔 から伝わる怖い話や作り話で相手を怖がらせて、戦う気をなくさせる方法です。良い悪 いは別にして、親が子供によく使いますよね。たとえば...、
    「暗くなる前に家に帰ってこないと人食いオニが出るよ。」
    「いい子にしていないと、サンタクロースが来ないよ。」
    「早く寝ないと、おばけが出るよ。」
    こうやって、本当かどうかわからない話で相手を怖がらせて、相手を自分の思い通り に動かす方法ですね。今も SNS などに本当かどうかわからない怖い話がたくさんあり ますよね。あれも、この「恐車の術」なのかもしれませんね。
    
    さあ、いかがでしたか。今日は、忍者の会話術について話しました。いや~、私も話
    しながら、すごく勉強になりました。これからは、マーケティングの広告や、ドラマを
    見る時や、小説を読むとき、人と話す時に、「あ~、これは今このテクニックを使って
    いるな」と分かっておもしろいんじゃないでしょうか。やっぱり忍者ってすごい。
    それでは、今週も日本語を使って楽しい時間を過ごせますように。 また来週の火曜日に。よい一日を!またね~。

------------------------------------------------------------------------

## 日本語-筆記 {.tabset}

### 語彙 {.tabset}

#### ウェブ・ニュース・平 {.tabset}

##### 1

山形県・やまがたけん・Yamagata Prefecture (Tohoku Area)   
鶴岡市・つるおかし・Tsuruoka City   
農家・のうか・farmer   
幅・はば・width・breadth   
ソーラーパネル・solar panel   
光・ひかり・light   
太陽・たいよう・sun   
自動・自動・automatic   
濁ります・にごります・to become muddy・to become cloudy・to become dull   
邪魔・じゃま・hindrance・obstacle・nuisance   
草・くさ・grass・weeds   
少なくする・すくなくする・to reduce   

山形県鶴岡市の会社が、薬を使わないで米を育てる農家の手伝いをするロボットを作りました   
A company in Tsuruoka City, Yamagata Prefecture, has created a robot that helps farmers grow rice without using chemicals (medicine)　

ソーラーパネルとGPSがついていて  
It's got a solar panel and GPS   

自動で動きます  
It runs automatically  

このロボットを田んぼに入れて、スクリューを回すと、水が濁ります   
When this robot is placed in a rice paddy and the screw is turned, the water becomes muddy!　　

米が育つのに邪魔になる草が大きくなりません   
Grasses that interfere with the growth of rice will not grow　　

ロボットを作った人は「将来、米を育てる農家の仕事を少なくすることが必要になります  
The person who created the robot said, "In the future, we will need to reduce the workload of farmers who grow rice  

田んぼの草をとるのは大変な仕事なので、ロボットで手伝いたいです」と話していました   
Weeding the rice paddies is a tough job, so I want to help with the robot," he said   

------------------------------------------------------------------------

##### 2

------------------------------------------------------------------------

##### 3

------------------------------------------------------------------------

##### 4

------------------------------------------------------------------------

##### 5

------------------------------------------------------------------------

#### ラーメン

日本で育ち・にほんでそだち`grow・breed in Japan`   
世界に進出した・せかいにしんしゅつ`advancing・expanding・emerging in the world`  
数多・あまた`many・a lot・much・multitude`  

    ラーメンという料理ほど独特な存在はなく  
    There is no more unique existence than the dish of ramen  

同時に・どうじに`coincident with・while・simultaneously`  
業態・ぎょうたい`business condition・line of business`  
独特・どくとく`peculiarity・uniqueness・characteristic`  
存在・そんざい`existence・being`

    同時に「ラーメン店」という業態も他の飲食店には見られない独特な業態である  
    At the same time, the "ramen restaurant" business is a unique type of business that cannot be found in any other restaurant   

源流・げんりゅう`source・origin of something continuous (language, culture, etc)`   
麺・めん`noodles`  

客観的・きゃっかんてき`objective`   
客観的に見て・きゃっかんてきにみて`looking objectively`   
客観的に見ても・きゃっかんてきにみても`even if you look at it objectively`   

    客観的に見ても間違いのないところである    
    There is no mistake even if you look at it objectively    

    日本で最初にラーメンを出したと言われる   
    Said to be the first to serve ramen in Japan   

来々軒・らいらいけん`Rairaiken`  　　　  
浅草・あさくさ`Asakusa`    
年創業・としそうぎょう`year of establishment`   　　

    日本で最初にラーメンを出したと言われる『来々軒』（浅草・1910年創業）は、 
    Rairaiken" (Asakusa, founded in 1910) is said to be the first ramen restaurant in Japan  
    
    焼売（シューマイ）や中華丼なども提供する大衆向けの中華料理店であった   
    It was a Chinese restaurant for the masses that also served siumai (fried pork dumplings) and Chinese rice bowls  

------------------------------------------------------------------------

### 文法 {.tabset}

#### ラーメン

(❖) 程・ほど`extent・degree・measure・limit・as much as`

① Compare A and B

AはBほど (adjective) ない    

    ・AはBほど背が高くない    
    ・AはBほどかわいくない 

AはBほど (verb) ない   

    ・AはBほど勉強しない  
    ・AはBほど飲まない  
  
② Not like ~・Not as ~   
    
ほどではありません・ほどではない  

    ・先生ほどではありません   
    ・先生ほどではないけどね   

③ Not as ~ as someone has imagined・thought・expected    
    
思ったほど・おもったほど`as ~ as someone thought`    
想像していたほど・そうぞうしていたほど`many as ~ as someone imagined`  
想像していたほど・きたいしていたほど`many as ~ as someone expected`    

    ・試験は、思ったほど難しくなかった  
    ・その店は評判ほど悪い店ではありませんでした
    ・僕は静香ちゃんが思っているほどモテないから心配しないで 

------------------------------------------------------------------------

# 

ϞϞ(๑⚈ ․̫ ⚈๑)∩